### ISSUE TITLE
Repo enhancement propose

### ISSUE THREAD

**Issue by gabriel19913** [lucasgdb/useful-dev-tools#170]
I suggest to list all tools/extensions in alphabetical order and maybe split the tables by category.
This will make the repo more organized and easy to read.

**Comment by lcnunes09** [comment]
Hello! I was about to create this issue. Can I contribute to this one?

**Comment by gabriel19913** [comment]
@lcnunes09 I was thinking to do this one too hahaha.
But what do you think of one be responsible to make the alphabetical order and the other to categorize?

**Comment by lcnunes09** [comment]
Sounds good to me! Which one do you prefer?

**Comment by gabriel19913** [comment]
I would like to order the lists, if it is ok for you.

**Comment by fernandakawasaki** [comment]
Hey! Just leaving a suggestion here: I think that it would be useful to add a recommendation to include the tools in alphabetical order in the CONTRIBUTING.md file.
